---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: otus-msa-hw8
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: payment-service
